### ISSUE TITLE
ModuleNotFoundError: No module named 'fcntl' on Windows 10

### ISSUE THREAD

**Issue by echidne** [davidbrochart/jpterm#48]
Os: Windows 10
Python: Python 3.11
Terminal: Powershell (Windows terminal)
How to reproduce : type 'jpterm' in prompt

Hi,
I wrote in Twitter but i think its more appropiate here.
Your library use the module 'fcntl' that is not available for Windows platforms
![image](https://github.com/davidbrochart/jpterm/assets/65033881/06a93aaf-8e5c-4261-83dd-43ffc1bcb1b3)

**Comment by davidbrochart** [comment]
Thanks for reporting the issue, #50 should fix it.

**Comment by echidne** [comment]
I confirm but I had to manually uninstall the txl dependencies since after uninstaling jpterm old ones were still there and install did not detect they were obsoletes
What i did:
- pip install -U jpterm => still the same issue
- pip uninstall + restart terminal + pip install git+https://github.com/davidbrochart/jpterm => still the same problem
- pip uninstall + manually uninstall all txl-* packages + pip install git+https://github.com/davidbrochart/jpterm => no problem
